---
- name: Set facts for python3
  set_fact:
    pip_executable: "pip3"
    python_executable: "python3"
  when: "use_python3|bool"

- name: Set facts for python2
  set_fact:
    pip_executable: "pip2"
    python_executable: "python2"
  when: "not use_python3|bool"

- name: Show use_python3 and pip_executable
  debug:
    msg: "Use Python3: {{ use_python3 }}; Pip Exe: {{ pip_executable }}; Python Exe: {{ python_executable }}"

- name: Install Celery
  pip:
    name: Celery
    state: present
    executable: "{{ pip_executable }}"

- name: Create Group for celery
  group:
    name: "{{ celery_group_name }}"
    system: yes
    state: present

- name: Create User for celery
  user:
    name: "{{ celery_user_name }}"
    groups: "{{ celery_group_name }},www-data"
    append: yes

- name: Create celery log directory
  file:
    path: "{{ celery_log_dir }}"
    state: directory
    owner: "{{ celery_user_name }}"
    group: "www-data"
    mode: 0775

- name: Create celery lib directory
  file:
    path: "/var/lib/celery"
    state: directory
    owner: "{{ celery_user_name }}"
    group: "www-data"
    mode: 0775

- name: Install celeryworker supervisord script
  template: 
    src: supervisor_celeryworker.conf.j2
    dest: "{{ supervisord_config_dir }}/conf.d/celeryworker.conf" 
    owner: "{{ supervisord_user_name }}"
    group: "{{ supervisord_group_name }}"
    mode: 0777 
  notify: restart celeryworker

- name: Install celerybeat supervisord script
  template: 
    src: supervisor_celerybeat.conf.j2
    dest: "{{ supervisord_config_dir }}/conf.d/celerybeat.conf" 
    owner: "{{ supervisord_user_name }}"
    group: "{{ supervisord_group_name }}"
    mode: 0777 
  notify: restart celerybeat
